# Generated by Django 5.2 on 2026-06-23 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hoteles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('capacidad', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('capacidad', models.PositiveIntegerField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('piso', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADA', 'Ocupada'), ('MANTENIMIENTO', 'Mantenimiento')], default='DISPONIBLE', max_length=20)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones', to='hoteles.hotel')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitaciones.tipohabitacion')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagen', models.URLField()),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='habitaciones.habitacion')),
            ],
        ),
        migrations.CreateModel(
            name='TipoHabitacionCama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('cama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitaciones.cama')),
                ('tipo_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitaciones.tipohabitacion')),
            ],
        ),
    ]
